# Generated by Django 4.2.4 on 2023-10-14 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoice_invoiceitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_status',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 3, 49, 36, 308797, tzinfo=datetime.timezone.utc)),
        ),
    ]
