# Generated by Django 4.2.4 on 2023-10-15 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aboutus_banner_teammember_alter_invoice_date_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_status',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
